### PR TITLE
Weather App

### PR DESCRIPTION
**Pull request by jamezjaz**
**This is a weather App project built with JavaScript, HTML, CSS, and Webpack**
In this project, the following features were implemented;

- Search input box
- Search button
- Button that toggles between degree Celsius and Fahrenheit
- Navbar

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @jamezjaz, great job on this project :100: Project works as expected. Except for a few changes we need to address before we can move on, kindly check the comments below:
- It changes its appearance based on the received data. Currently, the appearance do not change based on the data received. Let us kindly fix it. :slightly_smiling_face: 
- Let us fix our package.json file. Let us change our package.json script to this :+1: 
```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```
So we can run commands like `npm run start` as specified in the README file. Currently, this command does not work because of the missing script
- It uses either `promises` or `async/await`. Currently, we are not using any of these. Let us implement it. We can implement it when fetching data from the API :smile: 
- We are missing the `webpack-dev-server` in our package.json file. This will enable us to run the server :fireworks: 
- Kindly implement error handling for `promises` or `async/await` :partying_face: 

Once these are fixed, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
#### Hello Team 👋
#### Status: Changes Required ♻️

Great job so far! 👏👋
Let's cover a few details together to make your project better 😊⏬

### UI

- [ ] The weather information is not visible on some cases, please add the proper styling.

📸 Screenshot from the project
image

### Readme && package.json

- [ ] `npm run start` is not working. Please read carefully what the previous TSE wrote. 😇

📸 Screenshot from the project
image


## That's it, you can submit another code review request after making these changes ♻️😇

With all my respect 🙏
> Kubilay Caglayan | Technical Support Engineer

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @jamezjaz :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by jamezjaz** [comment]
Thank you very much

**Pull request merged**
